[package]
name = "motd"
version = "1.0.2"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
ansi_term = "0.11"
bytesize = "1.0.0"
clap = "2"
glob = "0.3.0"
itertools = "0.8.0"
libc = "0.2.50"
num_cpus = "1.10.0"
termsize = "0.1"
