[package]
name = "motd"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[features]
default = []
worker_thread = []

[dependencies]
ansi_term = "0.11"
glob = "0.3.0"
