[package]
name = "motd"
version = "1.1.1"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
ansi_term = "~0.12"
clap = "~2"
glob = "~0.3"
itertools = "~0.8"
libc = "~0.2"
num_cpus = "~1.11"
simple-error = "0.2"
termsize = "~0.1"
