[package]
name = "motd"
version = "0.1.0"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2018"

[profile.release]
panic = "abort"

[dependencies]
ansi_term = "0.11"
bytesize = "1.0.0"
glob = "0.3.0"
libc = "0.2.50"
num_cpus = "1.10.0"
