[package]
name = "motd"
version = "1.1.4"
authors = ["desbma <desbma@users.noreply.github.com>"]
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dependencies]
ansi_term = { version = "0.12.1", default-features = false }
anyhow = { version = "1.0.65", default-features = false, features = ["std", "backtrace"] }
clap =  { version = "3.2.22", default-features = false, features = ["std", "color"] }
glob =  { version = "0.3.0", default-features = false }
itertools =  { version = "0.10.4", default-features = false, features = ["use_std"] }
libc =  { version = "0.2.132", default-features = false }
num_cpus =  { version = "1.13.1", default-features = false }
termsize =  { version = "0.1.6", default-features = false }
